# services:
# create one service for mongo
# create one service for auth
services:
  mongo:
    container_name: mongo
    # pulling image mongo from dockerhub
    image: mongo:7.0
    # exposing port 27017
    ports:
      - "27017:27017"
    # volume is used to store data in your local hard disk in your system
    volumes:
      - mongo-data:/data/db

  auth-service:
    # command used to build the image, "./auth-service is the path where"
    # Dockerfile lives
    build: "./auth-service"
    # exposing port 3000 so app could run locally on port 3000 in local machine
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    # environment variables
    environment:
      - PORT=3000
      - DB_URI=mongodb://mongo:27017
      - JWT_SECRET=abcdefghijklmnop

  product-service:
    # command used to build the image, "./auth-service is the path where"
    build: "./product-service"
    # exposing port 3001 so app could run locally on port 3000 in local machine
    ports:
      - "3001:3001"
    # making sure mongo contains spins up first, since product service depends on it
    depends_on:
      - mongo
    # environment variables
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017

# volume to persist data for mongodb in hard disk
volumes:
  mongo-data:
